import type { StylisticRules } from "./types.gen";

export const rules: StylisticRules = {
  "@stylistic/array-bracket-newline": ["warn", { multiline: true }],
  "@stylistic/array-bracket-spacing": ["warn", "never"],
  "@stylistic/array-element-newline": ["warn", { consistent: true, multiline: true }],
  "@stylistic/arrow-parens": ["warn", "always"],
  "@stylistic/arrow-spacing": ["warn", { before: true, after: true }],
  "@stylistic/block-spacing": ["warn", "always"],
  "@stylistic/brace-style": ["warn", "1tbs", { allowSingleLine: true }],
  "@stylistic/comma-dangle": ["warn", "always-multiline"],
  "@stylistic/comma-spacing": ["warn", { before: false, after: true }],
  "@stylistic/comma-style": ["warn", "last"],
  "@stylistic/computed-property-spacing": ["warn", "never"],
  "@stylistic/curly-newline": ["warn", { consistent: true }],
  "@stylistic/dot-location": ["warn", "property"],
  "@stylistic/eol-last": ["warn", "always"],
  "@stylistic/function-call-argument-newline": ["warn", "consistent"],
  "@stylistic/function-call-spacing": ["warn", "never"],
  "@stylistic/function-paren-newline": ["warn", "multiline-arguments"],
  "@stylistic/generator-star-spacing": [
    "warn",
    {
      before: true,
      anonymous: "before",
      method: "before",
      shorthand: "before",
    },
  ],
  "@stylistic/implicit-arrow-linebreak": ["warn", "beside"],
  "@stylistic/indent": ["warn", 2, { VariableDeclarator: "first", flatTernaryExpressions: true }],
  "@stylistic/indent-binary-ops": ["warn", 2],
  "@stylistic/jsx-child-element-spacing": "warn",
  "@stylistic/jsx-closing-bracket-location": ["warn", "line-aligned"],
  "@stylistic/jsx-closing-tag-location": ["warn", "line-aligned"],
  "@stylistic/jsx-curly-brace-presence": ["warn", "never"],
  "@stylistic/jsx-curly-newline": ["warn", { multiline: "require", singleline: "forbid" }],
  "@stylistic/jsx-curly-spacing": ["warn", { children: { when: "always" }, attributes: { when: "never" } }],
  "@stylistic/jsx-equals-spacing": ["warn", "never"],
  "@stylistic/jsx-first-prop-new-line": ["warn", "multiline"],
  "@stylistic/jsx-function-call-newline": ["warn", "multiline"],
  "@stylistic/jsx-indent-props": ["warn", "first"],
  "@stylistic/jsx-max-props-per-line": ["warn", { maximum: 1, when: "multiline" }],
  "@stylistic/jsx-pascal-case": "warn",
  "@stylistic/jsx-quotes": ["warn", "prefer-double"],
  "@stylistic/jsx-self-closing-comp": "warn",
  "@stylistic/jsx-tag-spacing": [
    "warn",
    {
      closingSlash: "never",
      beforeSelfClosing: "always",
      afterOpening: "never",
      beforeClosing: "never",
    },
  ],
  "@stylistic/jsx-wrap-multilines": [
    "warn",
    {
      declaration: "parens-new-line",
      assignment: "parens-new-line",
      return: "parens-new-line",
      arrow: "parens-new-line",
      condition: "parens-new-line",
      logical: "parens-new-line",
      prop: "parens-new-line",
      propertyValue: "parens-new-line",
    },
  ],
  "@stylistic/key-spacing": ["warn", { beforeColon: false, afterColon: true, mode: "strict" }],
  "@stylistic/keyword-spacing": ["warn", { before: true, after: true }],
  "@stylistic/lines-between-class-members": [
    "warn",
    { enforce: [{ blankLine: "always", prev: "*", next: "method" }] },
    { exceptAfterOverload: true, exceptAfterSingleLine: true },
  ],
  "@stylistic/max-len": ["warn", { code: 120, tabWidth: 2, ignoreComments: true, ignoreUrls: true }],
  "@stylistic/max-statements-per-line": ["warn", { max: 1 }],
  "@stylistic/member-delimiter-style": [
    "warn",
    {
      multiline: {
        delimiter: "semi",
        requireLast: true,
      },
      singleline: {
        delimiter: "semi",
        requireLast: false,
      },
      multilineDetection: "brackets",
    },
  ],
  "@stylistic/multiline-comment-style": ["warn", "separate-lines", { checkJSDoc: false, checkExclamation: false }],
  "@stylistic/new-parens": ["warn", "always"],
  "@stylistic/no-confusing-arrow": ["warn", { onlyOneSimpleParam: true }],
  "@stylistic/no-extra-semi": "warn",
  "@stylistic/no-floating-decimal": "warn",
  "@stylistic/no-mixed-operators": "warn",
  "@stylistic/no-mixed-spaces-and-tabs": ["warn", "smart-tabs"],
  "@stylistic/no-multi-spaces": "warn",
  "@stylistic/no-multiple-empty-lines": ["warn", { max: 1, maxBOF: 0, maxEOF: 0 }],
  "@stylistic/no-trailing-spaces": "warn",
  "@stylistic/no-whitespace-before-property": "warn",
  "@stylistic/nonblock-statement-body-position": ["warn", "beside"],
  "@stylistic/object-curly-newline": ["warn", { multiline: true, consistent: true }],
  "@stylistic/object-curly-spacing": ["warn", "always", { emptyObjects: "never" }],
  "@stylistic/object-property-newline": ["warn", { allowAllPropertiesOnSameLine: true }],
  "@stylistic/one-var-declaration-per-line": ["warn", "initializations"],
  "@stylistic/padded-blocks": ["warn", "never"],
  "@stylistic/quote-props": ["warn", "as-needed"],
  "@stylistic/quotes": ["warn", "double", { avoidEscape: true }],
  "@stylistic/rest-spread-spacing": ["warn", "never"],
  "@stylistic/semi": "warn",
  "@stylistic/semi-spacing": "warn",
  "@stylistic/semi-style": ["warn", "last"],
  "@stylistic/space-before-blocks": ["warn", "always"],
  "@stylistic/space-before-function-paren": [
    "warn",
    {
      anonymous: "never",
      named: "never",
      asyncArrow: "always",
      catch: "always",
    },
  ],
  "@stylistic/space-in-parens": ["warn", "never"],
  "@stylistic/space-infix-ops": "warn",
  "@stylistic/space-unary-ops": ["warn", { words: true, nonwords: false }],
  "@stylistic/spaced-comment": ["warn", "always"],
  "@stylistic/switch-colon-spacing": ["warn", { after: true, before: false }],
  "@stylistic/template-curly-spacing": ["warn", "never"],
  "@stylistic/template-tag-spacing": ["warn", "never"],
  "@stylistic/type-annotation-spacing": ["warn", { overrides: { colon: { before: false, after: true } } }],
  "@stylistic/type-generic-spacing": "warn",
  "@stylistic/type-named-tuple-spacing": "warn",
  "@stylistic/wrap-iife": ["warn", "inside"],
  "@stylistic/yield-star-spacing": ["warn", "after"],
};
