import type { JavascriptCoreRules } from "./types.gen";

const core: JavascriptCoreRules = {
  "constructor-super": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-this-before-super": "error",
  "no-unassigned-vars": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-expressions": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": "error",
  "no-useless-assignment": "error",
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

const stylistic: JavascriptCoreRules = {
  "class-methods-use-this": "error",
  curly: ["error", "multi-line"],
  eqeqeq: ["error", "smart"],
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-delete-var": "error",
  "no-else-return": "error",
  "no-empty": "error",
  "no-empty-function": "error",
  "no-empty-static-block": "error",
  "no-eval": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-global-assign": "error",
  "no-implied-eval": "error",
  "no-iterator": "error",
  "no-lonely-if": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-object-constructor": "error",
  "no-octal": "error",
  "no-param-reassign": "error",
  "no-proto": "error",
  "no-redeclare": "error",
  "no-script-url": "error",
  "no-shadow-restricted-names": "error",
  "no-throw-literal": "error",
  "no-unused-labels": "error",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-escape": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "no-with": "error",
  "prefer-const": "error",
  "prefer-template": "error",
  "preserve-caught-error": "error",
  "require-await": "error",
  "require-yield": "error",
};

export const rules = { core, stylistic };
